export function getTopStocks() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(STOCK_DATA)
    }, 500)
  })
}

const STOCK_DATA = [
  {
    'symbol': 'AAPL',
    'company_name': 'Apple Inc.',
    'price': 150.25,
    'volume': 5000000,
    'market_cap': 2300000000000,
    'exchange': 'NASDAQ',
    'industry': 'Technology',
    'website': 'https://www.apple.com',
    'description': 'Apple Inc. is a multinational technology company that designs, manufactures, and markets consumer electronics, computer software, and online services.',
    'ceo': 'Tim Cook',
    'ipo': '1980-12-12',
  },
  {
    'symbol': 'MSFT',
    'company_name': 'Microsoft Corporation',
    'price': 300.50,
    'volume': undefined,
    'market_cap': 2200000000000,
    'exchange': 'NASDAQ',
    'industry': 'Technology',
    'website': 'https://www.microsoft.com',
    'description': 'Microsoft Corporation is a multinational technology company that produces, licenses, and sells computer software, consumer electronics, and personal computers.',
    'ceo': 'Satya Nadella',
    'ipo': '1986-03-13',
  },
  {
    'symbol': 'TSLA',
    'company_name': 'Tesla, Inc.',
    'price': 850.75,
    'volume': undefined,
    'market_cap': 900000000000,
    'exchange': 'NASDAQ',
    'industry': 'Automotive',
    'website': 'https://www.tesla.com',
    'description': 'Tesla, Inc. is an American electric vehicle and clean energy company known for its electric cars, solar products, and energy storage solutions.',
    'ceo': 'Elon Musk',
    'ipo': '2010-06-29',
  },
  {
    'symbol': 'SNE',
    'company_name': 'Sony Corporation',
    'price': 120.90,
    'volume': 800000,
    'market_cap': 1000000000000,
    'exchange': 'NYSE',
    'industry': 'Entertainment',
    'website': 'https://www.sony.com',
    'description': 'Sony Corporation is a Japanese multinational conglomerate corporation known for its electronics, gaming, entertainment, and financial services.',
    'ceo': 'Kenichiro Yoshida',
    'ipo': '1958-05-05',
  },
  {
    'symbol': 'GOOGL',
    'company_name': 'Alphabet Inc. (Google)',
    'price': 2800.30,
    'volume': 1500000,
    'market_cap': 2000000000000,
    'exchange': 'NASDAQ',
    'industry': 'Technology',
    'website': 'https://www.abc.xyz',
    'description': 'Alphabet Inc. is the parent company of Google, involved in various internet-related businesses, including search, online advertising, and cloud computing.',
    'ceo': 'Sundar Pichai',
    'ipo': '2004-08-19',
  },
  {
    'symbol': 'FB',
    'company_name': 'Meta Platforms, Inc. (Facebook)',
    'price': 330.40,
    'volume': 1000000,
    'market_cap': 950000000000,
    'exchange': 'NASDAQ',
    'industry': 'Social Media',
    'website': 'https://www.meta.com',
    'description': 'Meta Platforms, Inc. is a technology company that focuses on social media services and products, including Facebook, Instagram, and WhatsApp.',
    'ceo': 'Mark Zuckerberg',
    'ipo': '2012-05-18',
  },
  {
    'symbol': 'NFLX',
    'company_name': 'Netflix, Inc.',
    'price': 550.60,
    'volume': 700000,
    'market_cap': 180000000000,
    'exchange': 'NASDAQ',
    'industry': 'Streaming',
    'website': 'https://www.netflix.com',
    'description': 'Netflix, Inc. is an American subscription-based streaming service offering a wide variety of TV shows, movies, documentaries, and original content.',
    'ceo': 'Reed Hastings',
    'ipo': '2002-05-23',
  },
  {
    'symbol': 'UBER',
    'company_name': 'Uber Technologies, Inc.',
    'price': 45.80,
    'volume': 2000000,
    'market_cap': 70000000000,
    'exchange': 'NYSE',
    'industry': 'Transportation',
    'website': 'https://www.uber.com',
    'description': 'Uber Technologies, Inc. is a technology company that offers ride-sharing, food delivery, and other transportation services through its platform.',
    'ceo': 'Dara Khosrowshahi',
    'ipo': '2019-05-10',
  },
  {
    'symbol': 'AMZN',
    'company_name': 'Amazon.com, Inc.',
    'price': 3400.90,
    'volume': 2500000,
    'market_cap': 1800000000000,
    'exchange': 'NASDAQ',
    'industry': 'E-commerce',
    'website': 'https://www.amazon.com',
    'description': 'Amazon.com, Inc. is an American multinational technology and e-commerce company that focuses on online retail, cloud computing, and artificial intelligence.',
    'ceo': 'Andy Jassy',
    'ipo': '1997-05-15',
  },
  {
    'symbol': 'COST',
    'company_name': 'Costco Wholesale Corporation',
    'price': 500.20,
    'volume': 600000,
    'market_cap': 200000000000,
    'exchange': 'NASDAQ',
    'industry': 'Retail',
    'website': 'https://www.costco.com',
    'description': 'Costco Wholesale Corporation is a multinational corporation that operates a chain of membership-only warehouse clubs, offering a wide range of products.',
    'ceo': 'W. Craig Jelinek',
    'ipo': '1985-09-30',
  },
]